### ISSUE TITLE
Dependency graph in LR layout?

### ISSUE THREAD

**Issue by krlmlr** [glin/reactlog#2]
I'd like to understand better the dependencies between reactives in a larger Shiny app. The default `showReactLog()` uses a force-based layout for the graph, which in my case requires manually repositioning many nodes before I can make sense of the dependency structure.

I found this package through a [search for `graphStack`](https://github.com/search?q=graphstack+language%3Ar&type=Code), and I see two ways how I can achieve what I want with the help of this package:

1. Visualize the dependency graph (`.getGraph()` ?) with `dot` in LR layout.

2. Improve `react-graph.html` to use a different layout (not sure if D3 would support that).

Would you be interested in pursuing either option in the context of _reactlog_?

**Comment by glin** [comment]
There's a revamped reactive log in the works that I think does what you're looking for: https://github.com/rstudio/shiny/pull/2107, https://github.com/rstudio/shinyreactlog

I haven't played with it much, but it looks quite nice and doesn't use a force-directed graph. 

To try it out, I followed the instructions in the PR with a few differences:
```r
devtools::install_github("rstudio/shinyreactlog")
devtools::install_github("schloerke/shiny", ref = "barret/reactlog")

options(shiny.reactlog = TRUE)

shiny::runApp(system.file("examples/01_hello", package = "shiny"))

# ctrl/cmd+F3 to open the reactive graph -- I couldn't get shiny::showReactLog() to work
```

![image](https://user-images.githubusercontent.com/20401866/49123017-9a190e80-f27c-11e8-835e-0a9be2a3acbf.png)

**Comment by krlmlr** [comment]
Thanks a lot! I'll try this, closing for now.
